version: '3.8'

services:
  # FastAPI Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: timesheet_backend
    restart: unless-stopped
    ports:
      - "8130:8001"  # External port 8130 to avoid conflicts
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-apiuser}:${POSTGRES_PASSWORD}@${POSTGRES_HOST:-172.19.0.4}:5432/${POSTGRES_DB:-timesheet}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM:-HS256}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      ENVIRONMENT: production
      DOMAIN: ${DOMAIN}
    volumes:
      - ./app:/app/app:ro
    networks:
      - vps_project_app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  nginx_logs:
    driver: local

networks:
  vps_project_app_network:
    external: true
