name: Deploy to Production

on:
  push:
    branches: [ master ]

jobs:
  deploy-backend:
    name: Deploy Backend to VPS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 185.201.8.177 >> ~/.ssh/known_hosts

    - name: Deploy backend to VPS
      run: |
        chmod +x deploy-vps.sh
        ./deploy-vps.sh update

  deploy-frontend:
    name: Deploy Frontend to Firebase
    runs-on: ubuntu-latest
    needs: deploy-backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Build frontend
      run: |
        cd frontend
        npm run build

    - name: Deploy to Firebase
      run: |
        cd frontend
        echo "${{ secrets.FIREBASE_TOKEN }}" | firebase deploy --token-stdin --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}